# Generated by Django 5.2.7 on 2025-10-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_refreshtoken_deleted_at_refreshtoken_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
