# Generated by Django 5.2.7 on 2025-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_user_firstname_alter_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageattachment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereadreceipt',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagereadreceipt',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='obj',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='obj_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='MessageAttachment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
        migrations.DeleteModel(
            name='MessageReadReceipt',
        ),
    ]
