from django.urls import path
from apps.views import *

urlpatterns = [
    path('register/', register_user, name='register_user'),
    path('login/', login_user, name='login_user'),
    path('logout/', logout_user, name='logout_user'),
    path('users/', get_users, name='get_users'),
    path('me/', get_connected_user, name='get_connected_user'),
    path('me/update/', update_user, name='update_user'),
    path('supermarket/<str:supermarket_slug>/', get_supermarket, name='get_supermarket'),
    path('supermarkets/', list_supermarkets, name='list_supermarkets'),
    path('seller/supermarket/add/', create_supermarket, name='create_supermarket'),
    path('seller/supermarket/<str:supermarket_slug>/alter/', alter_supermarket, name='alter_supermarket'),
    path('seller/supermarket/<str:supermarket_slug>/delete/', delete_supermarket, name='delete_supermarket'),
    path('categories/', list_categories, name='list_categories'),
    path('category/add/', add_category, name='add_category'),
    path('category/<str:category_slug>/alter/', alter_category, name='alter_category'),
    path('category/<str:category_slug>/', get_category, name='get_category'),
    path('category/<str:category_slug>/delete/', delete_category, name='delete_category'),
    
    
    # Not tested yet
    path('products/', list_products, name='list_products'),
    path('product/add/', add_product, name='add_product'),
    path('product/<str:product_slug>/', get_product, name='get_product'),
    path('product/<str:product_slug>/images/add/', add_product_images, name='add_product_images'),
    path('product/<str:product_slug>/alter/', alter_product, name='alter_product'),
    path('product/<str:product_slug>/delete/', delete_product, name='delete_product'),
    path('supermarket/<str:supermarket_slug>/products/', list_supermarket_products, name='list_supermarket_products'),
    path('orders/', all_orders, name='list_orders'),
    path('supermarket/<str:supermarket_slug>/orders/', all_supermarket_orders, name='all_supermarket_orders'),
    path('customer/orders/', customer_orders, name='customer_orders'),
    path('customer/supermarket/<str:supermarket_slug>/orders/', all_customer_supermarket_orders, name='all_customer_supermarket_orders'),
    path('admin/orders/', all_orders_admin, name='all_orders_admin'),
    path('admin/supermarket/<str:supermarket_slug>/orders/', all_supermarket_orders_admin, name='all_supermarket_orders_admin'),
    path('delivery/orders/', delivery_orders, name='delivery_orders'),
    path('order/place/', place_order, name='place_order'),
    path('order/<str:order_slug>/', get_order, name='get_order'),
    path('order/<str:order_slug>/revoke/', revoke_order, name='revoke_order'),
    path('order/<str:order_slug>/pay/', pay_order, name='pay_order'),
    path('order/<str:order_slug>/revoke_payment/', revoke_payment, name='revoke_payment'),
    path('order/<str:order_slug>/assign_delivery/', assign_delivery, name='assign_delivery'),
    path('order/<str:order_slug>/delivery/start/', start_delivery, name='start_delivery'),
    path('order/<str:order_slug>/delivery/complete/', complete_delivery, name='complete_delivery'),
    path('order/<str:order_slug>/delivery/cancel/', cancel_delivery, name='cancel_delivery'),
    path('delivery/pending_orders/', delivery_pending_orders, name='delivery_pending_orders'),
    path('delivery/in_progress_orders/', delivery_in_progress_orders, name='delivery_in_progress_orders'),
    path('delivery/completed_orders/', delivery_completed_orders, name='delivery_completed_orders'),
    path('delivery/canceled_orders/', delivery_canceled_orders, name='delivery_canceled_orders'),
    path('deliveries/', all_deliveries, name='all_deliveries'),
    path('supermarket/<str:supermarket_slug>/deliveries/', supermarket_deliveries, name='supermarket_deliveries'),
    path('seller/deliveries/', seller_deliveries, name='seller_deliveries'),
    path('order/<str:order_slug>/delivery/note/add/', note_delivery, name='note_delivery'),
    path('order/<str:order_slug>/delivery/note/', get_delivery_note, name='get_delivery_note'),
    path('order/<str:order_slug>/delivery/note/delete/', delete_delivery_note, name='delete_delivery_note'),
    path('newsletter/subscribe/', add_newsletter_subscriber, name='add_newsletter_subscriber'),
    path('newsletter/unsubscribe/', remove_newsletter_subscriber, name='remove_newsletter_subscriber'),
    path('notifications/read_all/', read_all_notifications, name='read_all_notifications'),
    path('notifications/', list_notifications, name='list_notifications'),
    path('notification/<int:notification_slug>/read/', read_notification, name='read_notification'),
    
]